### PR TITLE
Fix memory example to import memory

### PR DESCRIPTION
**Pull request by lukewagner**
This patch addresses the issue raised in #7.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Nice one Luke!

**Comment by lukewagner** [comment]
@chrisdavidmills I think now we might need to update the dependent MDN pages' examples and explanations.  Is there an easy way to search all the MDN pages that link to memory.html?

**Comment by chrisdavidmills** [comment]
Just done that ;-)

**Comment by lukewagner** [comment]
Beautiful, looks great.

**Pull request merged**
